/** App-wide constants — routes, toast settings, etc. */

export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CHOOSE_ABBEY: '/choose-abbey',
  THE_EXPERIENCE: '/the-experience',
  LIFETIME_WARRANTY: '/lifetime-warranty',
  SIXTY_DAY_GUARANTEE: '/60-day-guarantee',
  SERVICES: '/services',
  CONTACT: '/contact',
  FLOORING: '/flooring',
  FLOORING_PRODUCT: '/flooring/:tab/:productId',
  LOVED_PRODUCTS: '/loved-products',
  CARPET_SALE: '/carpet-sale',
  HARDWOOD_SALE: '/hardwood-sale',
  LUXURY_VINYL_SALE: '/luxury-vinyl-sale',
  SAVINGS: '/savings',
  FINANCING: '/financing',
  CONSTRUCTION: '/construction',
  CORETEC_FLOORING: '/coretec-flooring',
  WATERPROOF_FLOORING: '/waterproof-flooring',
  CUSTOM_CABINETS: '/custom-cabinets',
  PREMIUM_COUNTERTOPS: '/premium-countertops',
  HOME_REMODELING: '/home-remodeling',
  PROJECT_GALLERY: '/project-gallery',
  PROJECT_DETAIL: '/project-gallery/:id',
  OUR_LOCATIONS: '/our-locations',
  LOGIN: '/login',

  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_EMAILS: '/admin/emails',
  ADMIN_LEADS: '/admin/leads',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_MARKETPLACE_ORDERS: '/admin/marketplace-orders',
  ADMIN_CASE_STUDIES: '/admin/case-studies',
  ADMIN_BLOG: '/admin/blog',
  ADMIN_JOBS: '/admin/jobs',
  ADMIN_PRICING: '/admin/pricing',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCTS_ADD: '/admin/products/add',
  ADMIN_PRODUCTS_EDIT: '/admin/products/:id/edit',
  ADMIN_LEADS_ENQUIRY: '/admin/leads-enquiry',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_PROFILE: '/admin/profile',
  ADMIN_GALLERY_ADMIN: '/admin/project-gallery',
  ADMIN_GALLERY_ADD: '/admin/project-gallery/add',
};

export const TOAST_CONFIG = {
  POSITION: 'top-right',
  DURATION: 7000,
};
